name: RyZerCore
api: 3.0.0
author: BauboLP
main: ryzerbe\core\RyZerBE
description: RyzerCore for RyzerBE
version: 2.0
loadbefore:
  - ChestOpening

permissions:
  ryzer.admin:
    default: op
  ryzer.vanish:
    default: op
  ryzer.rank:
    default: op
  ryzer.login:
    default: op
  ryzer.coins.admin:
    default: op
  ryzer.broadcast:
    default: op
  ryzer.teamchat:
    default: op
  ryzer.gamemode:
    default: op
  ryzer.gamemode.other:
    default: op