name: RyZerCore
api: 3.0.0
author: BauboLP
main: ryzerbe\core\RyZerBE
description: RyzerCore for RyzerBE
version: 2.0
loadbefore:
  - ChestOpening

load: STARTUP

permissions:
  ryzer.admin:
    default: op
  ryzer.vanish:
    default: op
  ryzer.rank:
    default: op
  ryzer.login:
    default: op
  ryzer.coins.admin:
    default: op
  ryzer.broadcast:
    default: op
  ryzer.teamchat:
    default: op
  ryzer.gamemode:
    default: op
  ryzer.gamemode.other:
    default: op
  ryzer.gamemode.creative:
    default: op
  ryzer.history:
    default: op
  ryzer.ban:
    default: op
  ryzer.ban.perma:
    default: op
  ryzer.unban:
    default: op
  ryzer.banentryreset:
    default: op
  ryzer.ban.edit.reasons:
    default: op
  ryzer.kick:
    default: op
  ryzer.joinme:
    default: op
  ryzer.togglerank:
    default: op
  ryzer.userinfo:
    default: op
  ryzer.nick:
    default: op
  ryzer.nick.list:
    default: op
  ryzer.joinme.tokens.add:
    default: op
  ryzer.coinboost.admin:
    default: op
  ryzer.chatmod.bypass:
    default: op